import type {
  EffectTag,
  EndlessPerkAction,
  EndlessPerkCategory,
  EndlessPerkDefinition,
  EndlessPerkId,
  EndlessPerkTrigger,
} from "./types";

function perk(
  id: EndlessPerkId,
  name: string,
  description: string,
  category: EndlessPerkCategory,
  trigger: EndlessPerkTrigger,
  actions: readonly EndlessPerkAction[],
  tags: readonly EffectTag[] = [],
): EndlessPerkDefinition {
  return {
    id,
    name,
    description,
    category,
    maxRank: 1,
    weight: 1,
    tags,
    rules: [{ trigger, actions }],
  };
}

export const ENDLESS_PERK_DEFINITIONS = [
  // 武器手艺：改变某把武器的事件链，不提供同质百分比面板。
  perk(
    "swordMarkReturn",
    "剑印回手",
    "剑标目标死后，剑折返并再索敌一次。",
    "weapon",
    {
      event: "markedTargetKilled",
      weaponId: "sword",
      counterScope: "target",
    },
    [{ kind: "returnAndRetarget", count: 1, target: "nearest" }],
    ["blade", "mark"],
  ),
  perk(
    "windDeflectShot",
    "借风偏箭",
    "友方弹体穿过扇风后，转向高生命敌并加速。",
    "weapon",
    { event: "projectileCrossedWind", requiredWeaponId: "fan" },
    [{ kind: "retargetAndAccelerate", value: 1.35, target: "highestHp" }],
    ["wind", "mechanism"],
  ),
  perk(
    "umbrellaGap",
    "伞下空当",
    "成功格挡后0.6秒推开近敌，并补一层伞护。",
    "weapon",
    { event: "guardSucceeded", weaponId: "umbrella", cooldownSeconds: 0.6 },
    [
      {
        kind: "pushAndGuard",
        radius: 148,
        durationSeconds: 0.6,
        count: 1,
      },
    ],
    ["rain", "guard"],
  ),
  perk(
    "scissorsCross",
    "合口一剪",
    "双剪轨迹相交时，夹击最近的标记敌人。",
    "weapon",
    { event: "scissorPathsCrossed", weaponId: "scissors" },
    [{ kind: "crossCutMarked", target: "nearest" }],
    ["craft", "blade", "mark"],
  ),
  perk(
    "ninePearl",
    "九珠清账",
    "同一目标吃到第九粒算珠时，触发三排珠。",
    "weapon",
    {
      event: "sameTargetPearlHit",
      weaponId: "abacus",
      every: 9,
      counterScope: "target",
    },
    [{ kind: "releasePearlRows", count: 3, target: "firstTarget" }],
    ["ledger"],
  ),
  perk(
    "thirdVolleyTurret",
    "三轮架弩",
    "每第三轮齐射留下一座持续4秒的地面弩台。",
    "weapon",
    {
      event: "crossbowVolleyCompleted",
      weaponId: "crossbow",
      every: 3,
      counterScope: "weapon",
    },
    [{ kind: "placeTemporaryTurret", durationSeconds: 4, count: 1 }],
    ["mechanism"],
  ),
  perk(
    "lastNoteReturn",
    "末音回拨",
    "泛音末跳以60%威力回到首目标一次。",
    "weapon",
    { event: "musicChainCompleted", weaponId: "pipa" },
    [
      {
        kind: "returnChainToFirst",
        value: 0.6,
        count: 1,
        target: "firstTarget",
      },
    ],
    ["music"],
  ),
  perk(
    "inkCrossStay",
    "交线留墨",
    "墨线多留1.5秒，交点同时触发一次墨爆。",
    "weapon",
    { event: "inkLinesCrossed", weaponId: "inkline" },
    [
      {
        kind: "extendInkAndBurstCross",
        durationSeconds: 1.5,
        count: 1,
      },
    ],
    ["craft"],
  ),
  perk(
    "lanternStoredFire",
    "灯灭存火",
    "影人消散时储一格灯火，下次灯格复制一次攻击。",
    "weapon",
    { event: "summonExpired", weaponId: "lantern" },
    [{ kind: "storeLanternFire", count: 1, maxActive: 1 }],
    ["shadow", "fire"],
  ),
  perk(
    "thunderRelay",
    "雷脚接线",
    "雷链末点留下持续3秒的接雷点。",
    "weapon",
    { event: "lightningChainCompleted", weaponId: "thunderSeal" },
    [{ kind: "leaveLightningRelay", durationSeconds: 3, count: 1 }],
    ["lightning", "spirit"],
  ),

  // 器盘走法：只改变游标、节点与收势的行走顺序。
  perk(
    "reverseCycle",
    "倒走一圈",
    "下一圈器盘游标改为反向行走。",
    "weave",
    { event: "weaveCycleStarted" },
    [{ kind: "reverseNextCycle", count: 1 }],
    ["wind"],
  ),
  perk(
    "dualCursor",
    "两头对走",
    "增加一个反向器盘游标；两个游标各保留55%效果。",
    "weave",
    { event: "weaveCycleStarted" },
    [{ kind: "addCounterCursor", count: 1, value: 0.55 }],
    ["spirit"],
  ),
  perk(
    "emptySlotCharge",
    "空位蓄力",
    "器盘游标经过空位时，为下一个节点蓄20%效果。",
    "weave",
    { event: "weaveNodePassed", minValue: 1 },
    [{ kind: "chargeNextNode", value: 0.2, target: "nextNode" }],
    ["mechanism"],
  ),
  perk(
    "everyThirdBack",
    "隔位回头",
    "每经过第三个节点，让前一个节点再执行一次。",
    "weave",
    { event: "weaveNodePassed", every: 3, counterScope: "global" },
    [{ kind: "repeatPreviousNode", count: 1 }],
    ["shadow"],
  ),
  perk(
    "firstNodeTwice",
    "头器再过",
    "每圈首节点执行两次。",
    "weave",
    { event: "weaveCycleStarted" },
    [{ kind: "repeatFirstNode", count: 1 }],
    ["mechanism"],
  ),
  perk(
    "slowHeavyFinish",
    "慢转重收",
    "器盘周期延长40%；收势后0.8秒以55%威力重放。",
    "weave",
    { event: "weaveFinishReleased" },
    [
      { kind: "scaleCycleAndFinish", value: 1.4, secondaryValue: 1 },
      { kind: "replayFinish", value: 0.55, durationSeconds: 0.8, count: 1 },
    ],
    ["guard"],
  ),
  perk(
    "fastLightFinish",
    "快转轻收",
    "器盘周期缩短25%，收势伤害降低20%。",
    "weave",
    { event: "weaveCycleStarted" },
    [{ kind: "scaleCycleAndFinish", value: 0.75, secondaryValue: 0.8 }],
    ["wind"],
  ),
  perk(
    "carryFinish",
    "余劲留盘",
    "收势的30%威力留给下一圈首节点。",
    "weave",
    { event: "weaveFinishReleased" },
    [{ kind: "carryFinishDamage", value: 0.3, target: "nextNode" }],
    ["spirit"],
  ),

  // 四时变化：通过具体掉落、天气和区域事件改变战场。
  perk(
    "springHealingLeaf",
    "新芽拾药",
    "拾取12个高档经验结后生一片恢复叶；20秒内最多存在1片。",
    "season",
    {
      event: "highTierPickupCollected",
      every: 12,
      cooldownSeconds: 20,
      counterScope: "global",
      season: "spring",
    },
    [{ kind: "spawnHealingLeaf", count: 1, maxActive: 1 }],
    ["spirit"],
  ),
  perk(
    "rainMergePearls",
    "雨水并珠",
    "雨时低值经验会更快合并，并更早开始吸附。",
    "season",
    { event: "pickupCreated", maxValue: 2, season: "spring" },
    [{ kind: "acceleratePickupMerge", value: 1.8, radius: 190 }],
    ["rain"],
  ),
  perk(
    "lotusConduct",
    "荷面导电",
    "持续区域命中敌人时，可把雷传给附近1个目标。",
    "season",
    { event: "zoneHit", season: "summer" },
    [{ kind: "conductLightningFromZone", count: 1, target: "nearest" }],
    ["rain", "lightning"],
  ),
  perk(
    "summerWindShot",
    "暑风推弹",
    "弹体穿过暑风后加速，并延长飞行时间。",
    "season",
    { event: "projectileCrossedWeather", season: "summer" },
    [
      {
        kind: "accelerateAndExtendProjectile",
        value: 1.35,
        durationSeconds: 0.6,
      },
    ],
    ["wind"],
  ),
  perk(
    "harvestBundle",
    "稻熟并收",
    "近距离连续击倒一群敌人时，把掉落结成一个高档经验结。",
    "season",
    { event: "multiKill", minValue: 3, season: "autumn" },
    [{ kind: "bundleKillDrops", count: 1, radius: 150 }],
    ["ledger"],
  ),
  perk(
    "autumnSweep",
    "秋风扫场",
    "每15秒把远处掉落扫向玩家。",
    "season",
    { event: "interval", cooldownSeconds: 15, season: "autumn" },
    [{ kind: "sweepDistantPickups", radius: 520 }],
    ["wind"],
  ),
  perk(
    "winterLanternWard",
    "冬灯护纸",
    "走马灯在场时，每20秒获得一次挡伤。",
    "season",
    {
      event: "interval",
      cooldownSeconds: 20,
      requiredWeaponId: "lantern",
      season: "winter",
    },
    [{ kind: "grantLanternGuard", count: 1, maxActive: 1 }],
    ["shadow", "guard"],
  ),
  perk(
    "frostEntrySlow",
    "霜线留步",
    "敌人首次进入墨线或持续区域时短暂减速；每个目标分别计冷却。",
    "season",
    {
      event: "enemyEnteredZone",
      cooldownSeconds: 3,
      counterScope: "target",
      season: "winter",
    },
    [{ kind: "slowFirstZoneEntry", value: 0.35, durationSeconds: 1.2 }],
    ["frost", "craft"],
  ),

  // 行旅自保：围绕拾取、形态与移动状态提供可读的生存窗口。
  perk(
    "highPickupWind",
    "拾珠回风",
    "拾取高档经验结时，发出一阵短风推开近敌。",
    "journey",
    { event: "highTierPickupCollected" },
    [{ kind: "emitPickupWind", radius: 132, durationSeconds: 0.3 }],
    ["wind", "guard"],
  ),
  perk(
    "lastPaperGuard",
    "破纸护命",
    "每90秒可把一次致命伤压到1点生命，并获得1秒无敌。",
    "journey",
    { event: "lethalDamage", cooldownSeconds: 90 },
    [
      {
        kind: "preventLethalDamage",
        value: 1,
        durationSeconds: 1,
      },
    ],
    ["guard"],
  ),
  perk(
    "humanSteady",
    "人形稳手",
    "展开成人形后的0.5秒获得一次受击减免窗口。",
    "journey",
    { event: "formChanged", form: "human" },
    [{ kind: "grantHumanGuard", durationSeconds: 0.5, count: 1 }],
    ["guard"],
  ),
  perk(
    "planeCharge",
    "飞行蓄势",
    "保持纸飞机形态3秒，强化下一次标志攻击。",
    "journey",
    { event: "formDuration", form: "plane", afterSeconds: 3 },
    [{ kind: "empowerNextSignatureAttack", value: 1.35, count: 1 }],
    ["wind", "mark"],
  ),
  perk(
    "sharpTurnPush",
    "急转卸力",
    "急转并展开时推开近敌；该效果有独立冷却。",
    "journey",
    { event: "sharpTurn", cooldownSeconds: 3 },
    [{ kind: "pushOnSharpTurn", radius: 138 }],
    ["wind", "guard"],
  ),
  perk(
    "idleRecovery",
    "止步养息",
    "停步0.8秒后缓慢回复；移动立即中断。",
    "journey",
    { event: "idleDuration", afterSeconds: 0.8, form: "human" },
    [{ kind: "healWhileIdle", value: 0.2 }],
    ["spirit"],
  ),
] as const satisfies readonly EndlessPerkDefinition[];

export const ENDLESS_PERKS_BY_ID: Readonly<
  Record<EndlessPerkId, EndlessPerkDefinition>
> = Object.freeze(
  Object.fromEntries(
    ENDLESS_PERK_DEFINITIONS.map((definition) => [definition.id, definition]),
  ) as Record<EndlessPerkId, EndlessPerkDefinition>,
);

export function getEndlessPerkDefinition(
  id: EndlessPerkId,
): EndlessPerkDefinition {
  return ENDLESS_PERKS_BY_ID[id];
}
